### ISSUE TITLE
Suggestion: Add distance to object as parameter

### ISSUE THREAD

**Issue by th23x** [iamso/CSS3-Tooltips#1]
Hi there,

really very cool CSS code, simple and straight forward without adding heavy JS to the tooltips - great!

One suggestion to add to CSS / LESS would be the distance to the object, so the tooltip can eg stay 3px away from the object it is pointing at.

Thanks for considering!

**Comment by iamso** [comment]
@th23x For even more customization options (and other improvements), check out my newer tooltip library https://github.com/iamso/tooltips.scss

**Comment by iamso** [comment]
@th23x If you prefer to use LESS, I have made a port of tooltips.scss https://github.com/iamso/tooltips.less
